plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

branches:
  - main
  - name: develop
    prerelease: '${name.replace(/^dev\//g, "dev-")}'