plugins:
  - "@semantic-release/commit-analyzer"


branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: develop*
    prerelease: '${name.replace(/^dev\//g, "dev-")}'
  - name: feature/*
    prerelease: '${name.replace(/^feature\//g, "feature-")}'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "hotfix-")}'