branches:
- main
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
# remove the comment from one of them according to your needs
- "@semantic-release/github"
- "@semantic-release/release-notes-generator"
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
- "@semantic-release/release-notes-generator"
- - "@semantic-release/exec"
  - prepareCmd: echo ${nextRelease.version} > VERSION.txt
- - "@semantic-release/git"
  - assets:
    - VERSION.txt