name: CD Pipeline

on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_NAME: simple-python-application
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || 'unknown' }}

jobs:
  deploy:
    needs: build-and-push
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    uses: davidlimacardoso/github-actions/.github/workflows/update-argocd-apps-helm-tag.yml@main
    with:
      project-name: simple-python-application
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || 'unknown' }}
      tag: ${{ needs.build-and-push.outputs.tag }}

