name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  PROJECT_NAME: simple-python-application

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          cd src/
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run tests
        run: |
          pytest

  semantic-release:
    needs: [test]
    name: Semantic Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write 
      issues: write 
      pull-requests: write
      id-token: write
    uses: davidlimacardoso/github-actions/.github/workflows/semantic-release.yml@main
    
  
  build-and-push:
    needs: [semantic-release]
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.semantic-release.outputs.release_version }}

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: src/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/:latest
          cache-to: type=inline