name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  release-drafter:
    permissions:
      contents: write
    uses: ./.github/release-drafter.yml@master

    name: release-drafter
