name: CI Pipeline

on:
  push:
    branches: 
      - main
      - develop

env:
  PROJECT_NAME: simple-python-application

permissions:
  contents: write
  actions: write

jobs:
  release-drafter:
    uses: ./.github/workflows/release-drafter.yml
    permissions:
      contents: write
      