name: Create Tag of Release

on:
  push:
    branches: 
      - main
      - develop

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 1.0.0  # It is recommended to specify a version range
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}