# Drafts next Release notes as PRs are merged into "main"
# see: https://github.com/marketplace/actions/release-drafter
name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission required to create a github release
      contents: write
      # write permission required for autolabeler
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
        # this file MUST be relative to '.github/'
          config-name: release-drafter-config.yml
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
